# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('investments', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('goal', 'Aporte em meta'), ('investment', 'Investimento')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='goals.goal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='investments.investment'),
        ),
    ]
